default:
  image: buildpack-deps

variables:
  GIT_SUBMODULE_STRATEGY: none

buildroot:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apt-get update && apt-get install -y rsync cpio bc
  script:
    - ./setup.sh
    - make -C build
  cache:
    key: buildroot-downloads
    untracked: true
    paths:
      - buildroot/dl/
  artifacts:
    paths:
      - build/images/

bundle:
  stage: build
  needs: [buildroot]
  before_script:
    - npm ci
  script:
    - mv build/images/bzImage src/machine/bzImage.bin
    - mv build/images/rootfs.squashfs src/machine/rootfs.bin
    - npm run build
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  needs: [bundle]
  script:
    - mv dist public
  pages: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
